name: stat20

channels:
- conda-forge

dependencies:
# Matches version in images/hub/Dockerfile
- jupyterhub==4.1.6

- jupyterlab==4.3.4
- notebook==7.3.2
- ipykernel = 6.29.5
- ipywidgets==8.1.5
- nbgitpuller==1.2.1
- appmode==1.0.0
- jupyter-resource-usage==1.1.0
- jupyter-server-proxy==4.4.0
- jupyter-rsession-proxy==2.2.1
- jupyterlab-git==0.50.2
- python==3.12.*

# syncthing for dropbox-like functionality
- jupyter-syncthing-proxy==1.0.3

# jupyter archival tool for easy user downloads
- jupyter-archive==3.4.0

# vscode
- jupyter-vscode-proxy==0.6
- code-server==4.96.2

# jupyterbook
- mystmd==1.3.19

# gh-scoped-creds needs a newer version of git than what jammy provides
- gh-scoped-creds==4.1
- git==2.47.0

- matplotlib=3.10.*
- shiny==1.2.1
- pip
- pip:
  - git-credential-helpers==0.2
  # Measure popularity of different packages in our hubs
  # https://discourse.jupyter.org/t/request-for-implementation-instrument-libraries-actively-used-by-users-on-a-jupyterhub/7994?u=yuvipanda
  - git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling
  - jupyter-shiny-proxy==1.1
  - jupyterlab-quarto==0.3.5
  - nb2pdf==0.6.2
  - nbpdfexport==0.2.1
  - nbconvert[webpdf]
