name: stat20

channels:
- conda-forge

dependencies:
# Matches version in images/hub/Dockerfile
- jupyterhub==4.1.6
- jupyterlab==4.2.5
- jupyter-server-proxy==4.4.0
- jupyter-rsession-proxy==2.2.1
- jupyter-syncthing-proxy==1.0.3
- jupyter-archive==3.4.0
- jupyter-resource-usage==1.1.0
- jupyter-vscode-proxy==0.6
- notebook==7.2.2
- nbconvert==7.6.0
- nbgitpuller==1.2.1
- ipywidgets==8.0.7
# bug w/notebook and traitlets: https://github.com/jupyter/notebook/issues/7048
#- traitlets=5.9.*
- matplotlib==3.8.3
- shiny==1.0.0
- appmode==1.0.0
- syncthing==1.22.2
- gh-scoped-creds==4.1
- pip
- pip:
  - git-credential-helpers==0.2
  # Measure popularity of different packages in our hubs
  # https://discourse.jupyter.org/t/request-for-implementation-instrument-libraries-actively-used-by-users-on-a-jupyterhub/7994?u=yuvipanda
  - git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling
  - jupyter-shiny-proxy==1.1
  - jupyterlab-quarto==0.3.5
  - nb2pdf==0.6.2
  - nbpdfexport==0.2.1
