name: stat20

channels:
- conda-forge

dependencies:
- syncthing==1.22.2
- jupyter-server-proxy==4.2.0
- jupyter-rsession-proxy==2.2.0
# bug w/notebook and traitlets: https://github.com/jupyter/notebook/issues/7048
- traitlets=5.9.*
- matplotlib==3.8.3
- pip:
  # old infra-requirements.txt
  - notebook==7.0.7
  - jupyterlab==4.0.11
  - nbgitpuller==1.2.1
  - jupyter-resource-usage==1.0.1
  - # Matches version in images/hub/Dockerfile
  - jupyterhub==4.1.6
  - appmode==0.8.0
  - ipywidgets==8.0.7
  - jupyter-tree-download==1.0.1
  - git-credential-helpers==0.2
  - # Measure popularity of different packages in our hubs
  - # https://discourse.jupyter.org/t/request-for-implementation-instrument-libraries-actively-used-by-users-on-a-jupyterhub/7994?u=yuvipanda
  - git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling
  - # RISE is useful for presentations - see https://github.com/berkeley-dsep-infra/datahub/issues/2527
  - RISE==5.7.1
  - # syncthing for dropbox-like functionality
  - jupyter-syncthing-proxy==1.0.3
  - # jupyter archival tool for easy user downloads
  - jupyter-archive==3.4.0
  # /old infra-requirements.txt
  # For push authentication to GitHub
  - gh-scoped-creds==4.1
  - jupyter-shiny-proxy==1.1
  # for notebook exporting
  - nbconvert==7.6.0
  - nb2pdf==0.6.2
  - nbpdfexport==0.2.1
  # for usage analysis dashboard (to be removed during sp 24 maintenance window)
  - shiny==0.8.1
